CREATE OR REPLACE transient TABLE BEACONFIRE.DEV_DB.group1_COMPANY_PROFILE_prestage
    as SELECT * FROM US_STOCKS_DAILY.PUBLIC.COMPANY_PROFILE;

CREATE OR REPLACE transient TABLE BEACONFIRE.DEV_DB.group1_stock_history_prestage
    as SELECT * FROM "US_STOCKS_DAILY"."PUBLIC".stock_history;