CREATE TABLE BEACONFIRE.DEV_DB.SYMBOLS_group1 as SELECT * FROM "US_STOCKS_DAILY"."PUBLIC"."SYMBOLS";
CREATE TABLE BEACONFIRE.DEV_DB.COMPANY_PROFILE_group1 as SELECT * FROM "US_STOCKS_DAILY"."PUBLIC"."COMPANY_PROFILE";
CREATE TABLE BEACONFIRE.DEV_DB.stock_history_group1 as SELECT * FROM "US_STOCKS_DAILY"."PUBLIC"."stock_history";